### ISSUE TITLE
AppManager.Instance.User == null

### ISSUE THREAD

**Issue by DeliciousOrange** [shane-lab/winforms-mvc#1]
hello, I have a question about your code . It is 
```
public override bool Loadable() 
	{
		return AppManager.Instance.User == null;
	}
```
what does it mean "Instance.User == null" ?　I can't find User. Looking forward to your reply.

**Comment by DeliciousOrange** [comment]
I just can't figure out under what conditions it is Loadable or not.

**Comment by shane-lab** [comment]
`Loadable` determines whether or not a controller can be used and thus be loaded. A success or fail handler is called accordingly, these can be overridden. The `User` part was to indicate that the controller can only be loaded based on the state of a signin. That's not part of this small library, though.

I can see how the README might be misleading in that way. I'm not maintaining this project, I am sure that there are other and better implementations of the lack of a MVC pattern in WinForms.
